title: Omijie Ogbeifun Precious
logo: Precious.png
description: A data analyst with experience of using Excel for nData analysis, Sql for data interrogation and manipulation and power Bi for creating business intelligent report.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
